title: site.title # *** Enter resource title here
github_repo_url: "" # ***Enter resource URL (in github pages) here
gh_edit_repository: "" # *** ENTER the github URL for your repo
ga_tracking: "" # *** This needs to be set up in Google Analytics once you know the website URL. Then the tracking code needs to be taken from Google Analytics and pasted here.

subtitle: footer.subtitle # *** Optional message that appears in the footer. Add value to en.yml and fr.yml
favicon_ico: "https://raw.githubusercontent.com/frdr-dfdr/resource-template/main/assets/img/favicon.ico"
nav_footer_logo_bottom: site.logo.bottom.file
nav_footer_logo_bottom_href: site.logo.bottom.href
nav_footer_logo_bottom_alt: site.logo.bottom.alt
nav_footer_logo_top: site.logo.top.file
nav_footer_logo_top_href: site.logo.bottom.href
nav_footer_logo_top_alt: site.logo.top.alt

languages: ["en", "fr"] # *** Leave as is for EN/FR or EN only documents. Change to ["fr", "en"] for FR only documents.
language_switcher: true # *** Show/Hide the language switcher button in the sidebar. Set to true for EN/FR documents and false for EN only or FR only documents.

#  _____       _   _   _          _      _
# | ____|   __| | (_) | |_       / \    | |__     ___   __   __   ___
# |  _|    / _` | | | | __|     / _ \   | '_ \   / _ \  \ \ / /  / _ \
# | |___  | (_| | | | | |_     / ___ \  | |_) | | (_) |  \ V /  |  __/
# |_____|  \__,_| |_|  \__|   /_/   \_\ |_.__/   \___/    \_/    \___|

navigation: true

remote_theme: frdr-dfdr/jtd-frdr
color_scheme: frdr

# Heading anchor links appear on hover over h1-h6 tags in page content
# allowing users to deep link to a particular heading on a page.
# Supports true (default) or false
heading_anchors: true

# Back to top link
back_to_top: true
back_to_top_text: site.back_to_top

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: footer.edit
gh_edit_branch: "main" # the branch that your docs is served from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-multiple-languages-plugin

exclude_from_localizations: []

license_url: "http://creativecommons.org/licenses/by/4.0/"
license_name: "Creative Commons Attribution 4.0 International License"
license_image_url: "https://i.creativecommons.org/l/by/4.0/88x31.png"

# Callout titles an colors
callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red
